swagger: '2.0'
info:
  title: Rupert API
  description: Backend API for multiuser tracker platform
  version: 0.0.1
host: localhost:34002
schemes:
  - https
basePath: /v1
produces:
  - application/json
paths:
  /users:
    get:
      summary: Get user lists
      description: |
        The users endpoint returns a list of the known users in the system.
      parameters:
        - name: limit
          in: query
          description: Number of results to return
          required: false
          type: boolean
        - name: offset
          in: query
          description: Number of records to offest the results py.
          required: false
          type: integer
          format: int32
      tags:
        - Users
      responses:
        '200':
          description: An array of users
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /users/{user_id}:
    get:
      summary: Fetches user object
      description: Fetches user object
      parameters:
        - name: user_id
          in: path
          description: user_id of the user to fetch
          required: true
          type: integer
          format: int64
      tags:
        - Users
      responses:
        '200':
          description: An array of users
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  User:
    type: object
    properties:
      user_id:
        type: integer
        description: 'Unique identifier representing a specific user'
      name:
        type: string
        description: Description of product.
      salt:
        type: string
        description: Randomly generated salt set upon user creation.
      hash:
        type: string
        description: Computed password hash
      created_on:
        type: string
        format: date-time
        description: Display name of product.
      updated_on:
        type: string
        format: date-time
        description: 'Capacity of product. For example, 4 people.'


  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
